//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedores.wsEstadoCuenta {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsEstadoCuenta.wsEstadoCuentaSoap")]
    public interface wsEstadoCuentaSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalPagado", ReplyAction="*")]
        Mantenedores.wsEstadoCuenta.GetTotalPagadoResponse GetTotalPagado(Mantenedores.wsEstadoCuenta.GetTotalPagadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTotalPagado", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsEstadoCuenta.GetTotalPagadoResponse> GetTotalPagadoAsync(Mantenedores.wsEstadoCuenta.GetTotalPagadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeudaTotal", ReplyAction="*")]
        int GetDeudaTotal(int curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeudaTotal", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetDeudaTotalAsync(int curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeudaAlumno", ReplyAction="*")]
        int GetDeudaAlumno(int curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeudaAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetDeudaAlumnoAsync(int curso);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalPagadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalPagado", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsEstadoCuenta.GetTotalPagadoRequestBody Body;
        
        public GetTotalPagadoRequest() {
        }
        
        public GetTotalPagadoRequest(Mantenedores.wsEstadoCuenta.GetTotalPagadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalPagadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int curso;
        
        public GetTotalPagadoRequestBody() {
        }
        
        public GetTotalPagadoRequestBody(string rut, int curso) {
            this.rut = rut;
            this.curso = curso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTotalPagadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTotalPagadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsEstadoCuenta.GetTotalPagadoResponseBody Body;
        
        public GetTotalPagadoResponse() {
        }
        
        public GetTotalPagadoResponse(Mantenedores.wsEstadoCuenta.GetTotalPagadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTotalPagadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetTotalPagadoResult;
        
        public GetTotalPagadoResponseBody() {
        }
        
        public GetTotalPagadoResponseBody(int GetTotalPagadoResult) {
            this.GetTotalPagadoResult = GetTotalPagadoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsEstadoCuentaSoapChannel : Mantenedores.wsEstadoCuenta.wsEstadoCuentaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsEstadoCuentaSoapClient : System.ServiceModel.ClientBase<Mantenedores.wsEstadoCuenta.wsEstadoCuentaSoap>, Mantenedores.wsEstadoCuenta.wsEstadoCuentaSoap {
        
        public wsEstadoCuentaSoapClient() {
        }
        
        public wsEstadoCuentaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsEstadoCuentaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEstadoCuentaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsEstadoCuentaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsEstadoCuenta.GetTotalPagadoResponse Mantenedores.wsEstadoCuenta.wsEstadoCuentaSoap.GetTotalPagado(Mantenedores.wsEstadoCuenta.GetTotalPagadoRequest request) {
            return base.Channel.GetTotalPagado(request);
        }
        
        public int GetTotalPagado(string rut, int curso) {
            Mantenedores.wsEstadoCuenta.GetTotalPagadoRequest inValue = new Mantenedores.wsEstadoCuenta.GetTotalPagadoRequest();
            inValue.Body = new Mantenedores.wsEstadoCuenta.GetTotalPagadoRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.curso = curso;
            Mantenedores.wsEstadoCuenta.GetTotalPagadoResponse retVal = ((Mantenedores.wsEstadoCuenta.wsEstadoCuentaSoap)(this)).GetTotalPagado(inValue);
            return retVal.Body.GetTotalPagadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsEstadoCuenta.GetTotalPagadoResponse> Mantenedores.wsEstadoCuenta.wsEstadoCuentaSoap.GetTotalPagadoAsync(Mantenedores.wsEstadoCuenta.GetTotalPagadoRequest request) {
            return base.Channel.GetTotalPagadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsEstadoCuenta.GetTotalPagadoResponse> GetTotalPagadoAsync(string rut, int curso) {
            Mantenedores.wsEstadoCuenta.GetTotalPagadoRequest inValue = new Mantenedores.wsEstadoCuenta.GetTotalPagadoRequest();
            inValue.Body = new Mantenedores.wsEstadoCuenta.GetTotalPagadoRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.curso = curso;
            return ((Mantenedores.wsEstadoCuenta.wsEstadoCuentaSoap)(this)).GetTotalPagadoAsync(inValue);
        }
        
        public int GetDeudaTotal(int curso) {
            return base.Channel.GetDeudaTotal(curso);
        }
        
        public System.Threading.Tasks.Task<int> GetDeudaTotalAsync(int curso) {
            return base.Channel.GetDeudaTotalAsync(curso);
        }
        
        public int GetDeudaAlumno(int curso) {
            return base.Channel.GetDeudaAlumno(curso);
        }
        
        public System.Threading.Tasks.Task<int> GetDeudaAlumnoAsync(int curso) {
            return base.Channel.GetDeudaAlumnoAsync(curso);
        }
    }
}
