//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedores.wsSendMail {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Task", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Mantenedores.wsSendMail.TaskOfString))]
    public partial class Task : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TaskOfString", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TaskOfString : Mantenedores.wsSendMail.Task {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsSendMail.wsSendMailSoap")]
    public interface wsSendMailSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento reciber del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMailPaid", ReplyAction="*")]
        Mantenedores.wsSendMail.SendMailPaidResponse SendMailPaid(Mantenedores.wsSendMail.SendMailPaidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMailPaid", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsSendMail.SendMailPaidResponse> SendMailPaidAsync(Mantenedores.wsSendMail.SendMailPaidRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento reciber del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMailActivityPaid", ReplyAction="*")]
        Mantenedores.wsSendMail.SendMailActivityPaidResponse SendMailActivityPaid(Mantenedores.wsSendMail.SendMailActivityPaidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMailActivityPaid", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsSendMail.SendMailActivityPaidResponse> SendMailActivityPaidAsync(Mantenedores.wsSendMail.SendMailActivityPaidRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailPaidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailPaid", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsSendMail.SendMailPaidRequestBody Body;
        
        public SendMailPaidRequest() {
        }
        
        public SendMailPaidRequest(Mantenedores.wsSendMail.SendMailPaidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailPaidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reciber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre_apoderado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string nombre_alumno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int monto_abonado;
        
        public SendMailPaidRequestBody() {
        }
        
        public SendMailPaidRequestBody(string reciber, string nombre_apoderado, string nombre_alumno, int monto_abonado) {
            this.reciber = reciber;
            this.nombre_apoderado = nombre_apoderado;
            this.nombre_alumno = nombre_alumno;
            this.monto_abonado = monto_abonado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailPaidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailPaidResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsSendMail.SendMailPaidResponseBody Body;
        
        public SendMailPaidResponse() {
        }
        
        public SendMailPaidResponse(Mantenedores.wsSendMail.SendMailPaidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailPaidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsSendMail.TaskOfString SendMailPaidResult;
        
        public SendMailPaidResponseBody() {
        }
        
        public SendMailPaidResponseBody(Mantenedores.wsSendMail.TaskOfString SendMailPaidResult) {
            this.SendMailPaidResult = SendMailPaidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailActivityPaidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailActivityPaid", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsSendMail.SendMailActivityPaidRequestBody Body;
        
        public SendMailActivityPaidRequest() {
        }
        
        public SendMailActivityPaidRequest(Mantenedores.wsSendMail.SendMailActivityPaidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailActivityPaidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string reciber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string nombre_apoderado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string curso;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int monto_abonado;
        
        public SendMailActivityPaidRequestBody() {
        }
        
        public SendMailActivityPaidRequestBody(string reciber, string nombre_apoderado, string curso, int monto_abonado) {
            this.reciber = reciber;
            this.nombre_apoderado = nombre_apoderado;
            this.curso = curso;
            this.monto_abonado = monto_abonado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailActivityPaidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailActivityPaidResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsSendMail.SendMailActivityPaidResponseBody Body;
        
        public SendMailActivityPaidResponse() {
        }
        
        public SendMailActivityPaidResponse(Mantenedores.wsSendMail.SendMailActivityPaidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMailActivityPaidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsSendMail.TaskOfString SendMailActivityPaidResult;
        
        public SendMailActivityPaidResponseBody() {
        }
        
        public SendMailActivityPaidResponseBody(Mantenedores.wsSendMail.TaskOfString SendMailActivityPaidResult) {
            this.SendMailActivityPaidResult = SendMailActivityPaidResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsSendMailSoapChannel : Mantenedores.wsSendMail.wsSendMailSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsSendMailSoapClient : System.ServiceModel.ClientBase<Mantenedores.wsSendMail.wsSendMailSoap>, Mantenedores.wsSendMail.wsSendMailSoap {
        
        public wsSendMailSoapClient() {
        }
        
        public wsSendMailSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsSendMailSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSendMailSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSendMailSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsSendMail.SendMailPaidResponse Mantenedores.wsSendMail.wsSendMailSoap.SendMailPaid(Mantenedores.wsSendMail.SendMailPaidRequest request) {
            return base.Channel.SendMailPaid(request);
        }
        
        public Mantenedores.wsSendMail.TaskOfString SendMailPaid(string reciber, string nombre_apoderado, string nombre_alumno, int monto_abonado) {
            Mantenedores.wsSendMail.SendMailPaidRequest inValue = new Mantenedores.wsSendMail.SendMailPaidRequest();
            inValue.Body = new Mantenedores.wsSendMail.SendMailPaidRequestBody();
            inValue.Body.reciber = reciber;
            inValue.Body.nombre_apoderado = nombre_apoderado;
            inValue.Body.nombre_alumno = nombre_alumno;
            inValue.Body.monto_abonado = monto_abonado;
            Mantenedores.wsSendMail.SendMailPaidResponse retVal = ((Mantenedores.wsSendMail.wsSendMailSoap)(this)).SendMailPaid(inValue);
            return retVal.Body.SendMailPaidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsSendMail.SendMailPaidResponse> Mantenedores.wsSendMail.wsSendMailSoap.SendMailPaidAsync(Mantenedores.wsSendMail.SendMailPaidRequest request) {
            return base.Channel.SendMailPaidAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsSendMail.SendMailPaidResponse> SendMailPaidAsync(string reciber, string nombre_apoderado, string nombre_alumno, int monto_abonado) {
            Mantenedores.wsSendMail.SendMailPaidRequest inValue = new Mantenedores.wsSendMail.SendMailPaidRequest();
            inValue.Body = new Mantenedores.wsSendMail.SendMailPaidRequestBody();
            inValue.Body.reciber = reciber;
            inValue.Body.nombre_apoderado = nombre_apoderado;
            inValue.Body.nombre_alumno = nombre_alumno;
            inValue.Body.monto_abonado = monto_abonado;
            return ((Mantenedores.wsSendMail.wsSendMailSoap)(this)).SendMailPaidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsSendMail.SendMailActivityPaidResponse Mantenedores.wsSendMail.wsSendMailSoap.SendMailActivityPaid(Mantenedores.wsSendMail.SendMailActivityPaidRequest request) {
            return base.Channel.SendMailActivityPaid(request);
        }
        
        public Mantenedores.wsSendMail.TaskOfString SendMailActivityPaid(string reciber, string nombre_apoderado, string curso, int monto_abonado) {
            Mantenedores.wsSendMail.SendMailActivityPaidRequest inValue = new Mantenedores.wsSendMail.SendMailActivityPaidRequest();
            inValue.Body = new Mantenedores.wsSendMail.SendMailActivityPaidRequestBody();
            inValue.Body.reciber = reciber;
            inValue.Body.nombre_apoderado = nombre_apoderado;
            inValue.Body.curso = curso;
            inValue.Body.monto_abonado = monto_abonado;
            Mantenedores.wsSendMail.SendMailActivityPaidResponse retVal = ((Mantenedores.wsSendMail.wsSendMailSoap)(this)).SendMailActivityPaid(inValue);
            return retVal.Body.SendMailActivityPaidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsSendMail.SendMailActivityPaidResponse> Mantenedores.wsSendMail.wsSendMailSoap.SendMailActivityPaidAsync(Mantenedores.wsSendMail.SendMailActivityPaidRequest request) {
            return base.Channel.SendMailActivityPaidAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsSendMail.SendMailActivityPaidResponse> SendMailActivityPaidAsync(string reciber, string nombre_apoderado, string curso, int monto_abonado) {
            Mantenedores.wsSendMail.SendMailActivityPaidRequest inValue = new Mantenedores.wsSendMail.SendMailActivityPaidRequest();
            inValue.Body = new Mantenedores.wsSendMail.SendMailActivityPaidRequestBody();
            inValue.Body.reciber = reciber;
            inValue.Body.nombre_apoderado = nombre_apoderado;
            inValue.Body.curso = curso;
            inValue.Body.monto_abonado = monto_abonado;
            return ((Mantenedores.wsSendMail.wsSendMailSoap)(this)).SendMailActivityPaidAsync(inValue);
        }
    }
}
