//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedores.wsPago {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pago", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Pago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private int AbonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Rut_alumnoField;
        
        private int Id_pagoField;
        
        private System.DateTime FechaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Abono {
            get {
                return this.AbonoField;
            }
            set {
                if ((this.AbonoField.Equals(value) != true)) {
                    this.AbonoField = value;
                    this.RaisePropertyChanged("Abono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Rut_alumno {
            get {
                return this.Rut_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.Rut_alumnoField, value) != true)) {
                    this.Rut_alumnoField = value;
                    this.RaisePropertyChanged("Rut_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Id_pago {
            get {
                return this.Id_pagoField;
            }
            set {
                if ((this.Id_pagoField.Equals(value) != true)) {
                    this.Id_pagoField = value;
                    this.RaisePropertyChanged("Id_pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumenPago", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResumenPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime FechaField;
        
        private int AbonoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Rut_alumnoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int Abono {
            get {
                return this.AbonoField;
            }
            set {
                if ((this.AbonoField.Equals(value) != true)) {
                    this.AbonoField = value;
                    this.RaisePropertyChanged("Abono");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Nombre_alumno {
            get {
                return this.Nombre_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_alumnoField, value) != true)) {
                    this.Nombre_alumnoField = value;
                    this.RaisePropertyChanged("Nombre_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Rut_alumno {
            get {
                return this.Rut_alumnoField;
            }
            set {
                if ((object.ReferenceEquals(this.Rut_alumnoField, value) != true)) {
                    this.Rut_alumnoField = value;
                    this.RaisePropertyChanged("Rut_alumno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Curso {
            get {
                return this.CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                    this.CursoField = value;
                    this.RaisePropertyChanged("Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoField, value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsPago.wsPagoSoap")]
    public interface wsPagoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllByAlumnoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByAlumno", ReplyAction="*")]
        Mantenedores.wsPago.GetAllByAlumnoResponse GetAllByAlumno(Mantenedores.wsPago.GetAllByAlumnoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByAlumno", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsPago.GetAllByAlumnoResponse> GetAllByAlumnoAsync(Mantenedores.wsPago.GetAllByAlumnoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllByCursoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByCurso", ReplyAction="*")]
        Mantenedores.wsPago.GetAllByCursoResponse GetAllByCurso(Mantenedores.wsPago.GetAllByCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByCurso", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsPago.GetAllByCursoResponse> GetAllByCursoAsync(Mantenedores.wsPago.GetAllByCursoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut_apoderado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByApoderado", ReplyAction="*")]
        Mantenedores.wsPago.GetAllByApoderadoResponse GetAllByApoderado(Mantenedores.wsPago.GetAllByApoderadoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByApoderado", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsPago.GetAllByApoderadoResponse> GetAllByApoderadoAsync(Mantenedores.wsPago.GetAllByApoderadoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut_alumno del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateSinglePaid", ReplyAction="*")]
        Mantenedores.wsPago.CreateSinglePaidResponse CreateSinglePaid(Mantenedores.wsPago.CreateSinglePaidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateSinglePaid", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsPago.CreateSinglePaidResponse> CreateSinglePaidAsync(Mantenedores.wsPago.CreateSinglePaidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateActivityPaid", ReplyAction="*")]
        bool CreateActivityPaid();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateActivityPaid", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> CreateActivityPaidAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllByAlumnoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllByAlumno", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsPago.GetAllByAlumnoRequestBody Body;
        
        public GetAllByAlumnoRequest() {
        }
        
        public GetAllByAlumnoRequest(Mantenedores.wsPago.GetAllByAlumnoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllByAlumnoRequestBody {
        
        public GetAllByAlumnoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllByAlumnoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllByAlumnoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsPago.GetAllByAlumnoResponseBody Body;
        
        public GetAllByAlumnoResponse() {
        }
        
        public GetAllByAlumnoResponse(Mantenedores.wsPago.GetAllByAlumnoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllByAlumnoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsPago.Pago[] GetAllByAlumnoResult;
        
        public GetAllByAlumnoResponseBody() {
        }
        
        public GetAllByAlumnoResponseBody(Mantenedores.wsPago.Pago[] GetAllByAlumnoResult) {
            this.GetAllByAlumnoResult = GetAllByAlumnoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllByCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllByCurso", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsPago.GetAllByCursoRequestBody Body;
        
        public GetAllByCursoRequest() {
        }
        
        public GetAllByCursoRequest(Mantenedores.wsPago.GetAllByCursoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllByCursoRequestBody {
        
        public GetAllByCursoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllByCursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllByCursoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsPago.GetAllByCursoResponseBody Body;
        
        public GetAllByCursoResponse() {
        }
        
        public GetAllByCursoResponse(Mantenedores.wsPago.GetAllByCursoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllByCursoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsPago.Pago[] GetAllByCursoResult;
        
        public GetAllByCursoResponseBody() {
        }
        
        public GetAllByCursoResponseBody(Mantenedores.wsPago.Pago[] GetAllByCursoResult) {
            this.GetAllByCursoResult = GetAllByCursoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllByApoderadoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllByApoderado", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsPago.GetAllByApoderadoRequestBody Body;
        
        public GetAllByApoderadoRequest() {
        }
        
        public GetAllByApoderadoRequest(Mantenedores.wsPago.GetAllByApoderadoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllByApoderadoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut_apoderado;
        
        public GetAllByApoderadoRequestBody() {
        }
        
        public GetAllByApoderadoRequestBody(string rut_apoderado) {
            this.rut_apoderado = rut_apoderado;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllByApoderadoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllByApoderadoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsPago.GetAllByApoderadoResponseBody Body;
        
        public GetAllByApoderadoResponse() {
        }
        
        public GetAllByApoderadoResponse(Mantenedores.wsPago.GetAllByApoderadoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllByApoderadoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsPago.ResumenPago[] GetAllByApoderadoResult;
        
        public GetAllByApoderadoResponseBody() {
        }
        
        public GetAllByApoderadoResponseBody(Mantenedores.wsPago.ResumenPago[] GetAllByApoderadoResult) {
            this.GetAllByApoderadoResult = GetAllByApoderadoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSinglePaidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateSinglePaid", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsPago.CreateSinglePaidRequestBody Body;
        
        public CreateSinglePaidRequest() {
        }
        
        public CreateSinglePaidRequest(Mantenedores.wsPago.CreateSinglePaidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateSinglePaidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int abono;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rut_alumno;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id_tipo_pago;
        
        public CreateSinglePaidRequestBody() {
        }
        
        public CreateSinglePaidRequestBody(int abono, string rut_alumno, int id_tipo_pago) {
            this.abono = abono;
            this.rut_alumno = rut_alumno;
            this.id_tipo_pago = id_tipo_pago;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateSinglePaidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateSinglePaidResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsPago.CreateSinglePaidResponseBody Body;
        
        public CreateSinglePaidResponse() {
        }
        
        public CreateSinglePaidResponse(Mantenedores.wsPago.CreateSinglePaidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateSinglePaidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateSinglePaidResult;
        
        public CreateSinglePaidResponseBody() {
        }
        
        public CreateSinglePaidResponseBody(bool CreateSinglePaidResult) {
            this.CreateSinglePaidResult = CreateSinglePaidResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsPagoSoapChannel : Mantenedores.wsPago.wsPagoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsPagoSoapClient : System.ServiceModel.ClientBase<Mantenedores.wsPago.wsPagoSoap>, Mantenedores.wsPago.wsPagoSoap {
        
        public wsPagoSoapClient() {
        }
        
        public wsPagoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsPagoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPagoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsPagoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsPago.GetAllByAlumnoResponse Mantenedores.wsPago.wsPagoSoap.GetAllByAlumno(Mantenedores.wsPago.GetAllByAlumnoRequest request) {
            return base.Channel.GetAllByAlumno(request);
        }
        
        public Mantenedores.wsPago.Pago[] GetAllByAlumno() {
            Mantenedores.wsPago.GetAllByAlumnoRequest inValue = new Mantenedores.wsPago.GetAllByAlumnoRequest();
            inValue.Body = new Mantenedores.wsPago.GetAllByAlumnoRequestBody();
            Mantenedores.wsPago.GetAllByAlumnoResponse retVal = ((Mantenedores.wsPago.wsPagoSoap)(this)).GetAllByAlumno(inValue);
            return retVal.Body.GetAllByAlumnoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsPago.GetAllByAlumnoResponse> Mantenedores.wsPago.wsPagoSoap.GetAllByAlumnoAsync(Mantenedores.wsPago.GetAllByAlumnoRequest request) {
            return base.Channel.GetAllByAlumnoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsPago.GetAllByAlumnoResponse> GetAllByAlumnoAsync() {
            Mantenedores.wsPago.GetAllByAlumnoRequest inValue = new Mantenedores.wsPago.GetAllByAlumnoRequest();
            inValue.Body = new Mantenedores.wsPago.GetAllByAlumnoRequestBody();
            return ((Mantenedores.wsPago.wsPagoSoap)(this)).GetAllByAlumnoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsPago.GetAllByCursoResponse Mantenedores.wsPago.wsPagoSoap.GetAllByCurso(Mantenedores.wsPago.GetAllByCursoRequest request) {
            return base.Channel.GetAllByCurso(request);
        }
        
        public Mantenedores.wsPago.Pago[] GetAllByCurso() {
            Mantenedores.wsPago.GetAllByCursoRequest inValue = new Mantenedores.wsPago.GetAllByCursoRequest();
            inValue.Body = new Mantenedores.wsPago.GetAllByCursoRequestBody();
            Mantenedores.wsPago.GetAllByCursoResponse retVal = ((Mantenedores.wsPago.wsPagoSoap)(this)).GetAllByCurso(inValue);
            return retVal.Body.GetAllByCursoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsPago.GetAllByCursoResponse> Mantenedores.wsPago.wsPagoSoap.GetAllByCursoAsync(Mantenedores.wsPago.GetAllByCursoRequest request) {
            return base.Channel.GetAllByCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsPago.GetAllByCursoResponse> GetAllByCursoAsync() {
            Mantenedores.wsPago.GetAllByCursoRequest inValue = new Mantenedores.wsPago.GetAllByCursoRequest();
            inValue.Body = new Mantenedores.wsPago.GetAllByCursoRequestBody();
            return ((Mantenedores.wsPago.wsPagoSoap)(this)).GetAllByCursoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsPago.GetAllByApoderadoResponse Mantenedores.wsPago.wsPagoSoap.GetAllByApoderado(Mantenedores.wsPago.GetAllByApoderadoRequest request) {
            return base.Channel.GetAllByApoderado(request);
        }
        
        public Mantenedores.wsPago.ResumenPago[] GetAllByApoderado(string rut_apoderado) {
            Mantenedores.wsPago.GetAllByApoderadoRequest inValue = new Mantenedores.wsPago.GetAllByApoderadoRequest();
            inValue.Body = new Mantenedores.wsPago.GetAllByApoderadoRequestBody();
            inValue.Body.rut_apoderado = rut_apoderado;
            Mantenedores.wsPago.GetAllByApoderadoResponse retVal = ((Mantenedores.wsPago.wsPagoSoap)(this)).GetAllByApoderado(inValue);
            return retVal.Body.GetAllByApoderadoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsPago.GetAllByApoderadoResponse> Mantenedores.wsPago.wsPagoSoap.GetAllByApoderadoAsync(Mantenedores.wsPago.GetAllByApoderadoRequest request) {
            return base.Channel.GetAllByApoderadoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsPago.GetAllByApoderadoResponse> GetAllByApoderadoAsync(string rut_apoderado) {
            Mantenedores.wsPago.GetAllByApoderadoRequest inValue = new Mantenedores.wsPago.GetAllByApoderadoRequest();
            inValue.Body = new Mantenedores.wsPago.GetAllByApoderadoRequestBody();
            inValue.Body.rut_apoderado = rut_apoderado;
            return ((Mantenedores.wsPago.wsPagoSoap)(this)).GetAllByApoderadoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsPago.CreateSinglePaidResponse Mantenedores.wsPago.wsPagoSoap.CreateSinglePaid(Mantenedores.wsPago.CreateSinglePaidRequest request) {
            return base.Channel.CreateSinglePaid(request);
        }
        
        public bool CreateSinglePaid(int abono, string rut_alumno, int id_tipo_pago) {
            Mantenedores.wsPago.CreateSinglePaidRequest inValue = new Mantenedores.wsPago.CreateSinglePaidRequest();
            inValue.Body = new Mantenedores.wsPago.CreateSinglePaidRequestBody();
            inValue.Body.abono = abono;
            inValue.Body.rut_alumno = rut_alumno;
            inValue.Body.id_tipo_pago = id_tipo_pago;
            Mantenedores.wsPago.CreateSinglePaidResponse retVal = ((Mantenedores.wsPago.wsPagoSoap)(this)).CreateSinglePaid(inValue);
            return retVal.Body.CreateSinglePaidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsPago.CreateSinglePaidResponse> Mantenedores.wsPago.wsPagoSoap.CreateSinglePaidAsync(Mantenedores.wsPago.CreateSinglePaidRequest request) {
            return base.Channel.CreateSinglePaidAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsPago.CreateSinglePaidResponse> CreateSinglePaidAsync(int abono, string rut_alumno, int id_tipo_pago) {
            Mantenedores.wsPago.CreateSinglePaidRequest inValue = new Mantenedores.wsPago.CreateSinglePaidRequest();
            inValue.Body = new Mantenedores.wsPago.CreateSinglePaidRequestBody();
            inValue.Body.abono = abono;
            inValue.Body.rut_alumno = rut_alumno;
            inValue.Body.id_tipo_pago = id_tipo_pago;
            return ((Mantenedores.wsPago.wsPagoSoap)(this)).CreateSinglePaidAsync(inValue);
        }
        
        public bool CreateActivityPaid() {
            return base.Channel.CreateActivityPaid();
        }
        
        public System.Threading.Tasks.Task<bool> CreateActivityPaidAsync() {
            return base.Channel.CreateActivityPaidAsync();
        }
    }
}
