//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedores.wsActividadPago {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResumenActividadPago", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ResumenActividadPago : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.DateTime FechaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        private int MontoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime Fecha {
            get {
                return this.FechaField;
            }
            set {
                if ((this.FechaField.Equals(value) != true)) {
                    this.FechaField = value;
                    this.RaisePropertyChanged("Fecha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Curso {
            get {
                return this.CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.CursoField, value) != true)) {
                    this.CursoField = value;
                    this.RaisePropertyChanged("Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Monto {
            get {
                return this.MontoField;
            }
            set {
                if ((this.MontoField.Equals(value) != true)) {
                    this.MontoField = value;
                    this.RaisePropertyChanged("Monto");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsActividadPago.wsActividadPagoSoap")]
    public interface wsActividadPagoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento descripcion del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePaid", ReplyAction="*")]
        Mantenedores.wsActividadPago.CreatePaidResponse CreatePaid(Mantenedores.wsActividadPago.CreatePaidRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePaid", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsActividadPago.CreatePaidResponse> CreatePaidAsync(Mantenedores.wsActividadPago.CreatePaidRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllByCursoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByCurso", ReplyAction="*")]
        Mantenedores.wsActividadPago.GetAllByCursoResponse GetAllByCurso(Mantenedores.wsActividadPago.GetAllByCursoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllByCurso", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsActividadPago.GetAllByCursoResponse> GetAllByCursoAsync(Mantenedores.wsActividadPago.GetAllByCursoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePaidRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePaid", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsActividadPago.CreatePaidRequestBody Body;
        
        public CreatePaidRequest() {
        }
        
        public CreatePaidRequest(Mantenedores.wsActividadPago.CreatePaidRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePaidRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string descripcion;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int monto;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int id_curso;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime fecha;
        
        public CreatePaidRequestBody() {
        }
        
        public CreatePaidRequestBody(string descripcion, int monto, int id_curso, System.DateTime fecha) {
            this.descripcion = descripcion;
            this.monto = monto;
            this.id_curso = id_curso;
            this.fecha = fecha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePaidResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePaidResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsActividadPago.CreatePaidResponseBody Body;
        
        public CreatePaidResponse() {
        }
        
        public CreatePaidResponse(Mantenedores.wsActividadPago.CreatePaidResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePaidResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreatePaidResult;
        
        public CreatePaidResponseBody() {
        }
        
        public CreatePaidResponseBody(bool CreatePaidResult) {
            this.CreatePaidResult = CreatePaidResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllByCursoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllByCurso", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsActividadPago.GetAllByCursoRequestBody Body;
        
        public GetAllByCursoRequest() {
        }
        
        public GetAllByCursoRequest(Mantenedores.wsActividadPago.GetAllByCursoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllByCursoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_curso;
        
        public GetAllByCursoRequestBody() {
        }
        
        public GetAllByCursoRequestBody(int id_curso) {
            this.id_curso = id_curso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllByCursoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllByCursoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsActividadPago.GetAllByCursoResponseBody Body;
        
        public GetAllByCursoResponse() {
        }
        
        public GetAllByCursoResponse(Mantenedores.wsActividadPago.GetAllByCursoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllByCursoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsActividadPago.ResumenActividadPago[] GetAllByCursoResult;
        
        public GetAllByCursoResponseBody() {
        }
        
        public GetAllByCursoResponseBody(Mantenedores.wsActividadPago.ResumenActividadPago[] GetAllByCursoResult) {
            this.GetAllByCursoResult = GetAllByCursoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsActividadPagoSoapChannel : Mantenedores.wsActividadPago.wsActividadPagoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsActividadPagoSoapClient : System.ServiceModel.ClientBase<Mantenedores.wsActividadPago.wsActividadPagoSoap>, Mantenedores.wsActividadPago.wsActividadPagoSoap {
        
        public wsActividadPagoSoapClient() {
        }
        
        public wsActividadPagoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsActividadPagoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsActividadPagoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsActividadPagoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsActividadPago.CreatePaidResponse Mantenedores.wsActividadPago.wsActividadPagoSoap.CreatePaid(Mantenedores.wsActividadPago.CreatePaidRequest request) {
            return base.Channel.CreatePaid(request);
        }
        
        public bool CreatePaid(string descripcion, int monto, int id_curso, System.DateTime fecha) {
            Mantenedores.wsActividadPago.CreatePaidRequest inValue = new Mantenedores.wsActividadPago.CreatePaidRequest();
            inValue.Body = new Mantenedores.wsActividadPago.CreatePaidRequestBody();
            inValue.Body.descripcion = descripcion;
            inValue.Body.monto = monto;
            inValue.Body.id_curso = id_curso;
            inValue.Body.fecha = fecha;
            Mantenedores.wsActividadPago.CreatePaidResponse retVal = ((Mantenedores.wsActividadPago.wsActividadPagoSoap)(this)).CreatePaid(inValue);
            return retVal.Body.CreatePaidResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsActividadPago.CreatePaidResponse> Mantenedores.wsActividadPago.wsActividadPagoSoap.CreatePaidAsync(Mantenedores.wsActividadPago.CreatePaidRequest request) {
            return base.Channel.CreatePaidAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsActividadPago.CreatePaidResponse> CreatePaidAsync(string descripcion, int monto, int id_curso, System.DateTime fecha) {
            Mantenedores.wsActividadPago.CreatePaidRequest inValue = new Mantenedores.wsActividadPago.CreatePaidRequest();
            inValue.Body = new Mantenedores.wsActividadPago.CreatePaidRequestBody();
            inValue.Body.descripcion = descripcion;
            inValue.Body.monto = monto;
            inValue.Body.id_curso = id_curso;
            inValue.Body.fecha = fecha;
            return ((Mantenedores.wsActividadPago.wsActividadPagoSoap)(this)).CreatePaidAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsActividadPago.GetAllByCursoResponse Mantenedores.wsActividadPago.wsActividadPagoSoap.GetAllByCurso(Mantenedores.wsActividadPago.GetAllByCursoRequest request) {
            return base.Channel.GetAllByCurso(request);
        }
        
        public Mantenedores.wsActividadPago.ResumenActividadPago[] GetAllByCurso(int id_curso) {
            Mantenedores.wsActividadPago.GetAllByCursoRequest inValue = new Mantenedores.wsActividadPago.GetAllByCursoRequest();
            inValue.Body = new Mantenedores.wsActividadPago.GetAllByCursoRequestBody();
            inValue.Body.id_curso = id_curso;
            Mantenedores.wsActividadPago.GetAllByCursoResponse retVal = ((Mantenedores.wsActividadPago.wsActividadPagoSoap)(this)).GetAllByCurso(inValue);
            return retVal.Body.GetAllByCursoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsActividadPago.GetAllByCursoResponse> Mantenedores.wsActividadPago.wsActividadPagoSoap.GetAllByCursoAsync(Mantenedores.wsActividadPago.GetAllByCursoRequest request) {
            return base.Channel.GetAllByCursoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsActividadPago.GetAllByCursoResponse> GetAllByCursoAsync(int id_curso) {
            Mantenedores.wsActividadPago.GetAllByCursoRequest inValue = new Mantenedores.wsActividadPago.GetAllByCursoRequest();
            inValue.Body = new Mantenedores.wsActividadPago.GetAllByCursoRequestBody();
            inValue.Body.id_curso = id_curso;
            return ((Mantenedores.wsActividadPago.wsActividadPagoSoap)(this)).GetAllByCursoAsync(inValue);
        }
    }
}
