//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedores.wsContrato {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Contrato", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Contrato : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int Id_contratoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        private System.DateTime Fecha_emisionField;
        
        private int Id_cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id_contrato {
            get {
                return this.Id_contratoField;
            }
            set {
                if ((this.Id_contratoField.Equals(value) != true)) {
                    this.Id_contratoField = value;
                    this.RaisePropertyChanged("Id_contrato");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Fecha_emision {
            get {
                return this.Fecha_emisionField;
            }
            set {
                if ((this.Fecha_emisionField.Equals(value) != true)) {
                    this.Fecha_emisionField = value;
                    this.RaisePropertyChanged("Fecha_emision");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Id_curso {
            get {
                return this.Id_cursoField;
            }
            set {
                if ((this.Id_cursoField.Equals(value) != true)) {
                    this.Id_cursoField = value;
                    this.RaisePropertyChanged("Id_curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Documento {
            get {
                return this.DocumentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentoField, value) != true)) {
                    this.DocumentoField = value;
                    this.RaisePropertyChanged("Documento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsContrato.wsContratoSoap")]
    public interface wsContratoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento traerUnContratoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerUnContrato", ReplyAction="*")]
        Mantenedores.wsContrato.traerUnContratoResponse traerUnContrato(Mantenedores.wsContrato.traerUnContratoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerUnContrato", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsContrato.traerUnContratoResponse> traerUnContratoAsync(Mantenedores.wsContrato.traerUnContratoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetContratosResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContratos", ReplyAction="*")]
        Mantenedores.wsContrato.GetContratosResponse GetContratos(Mantenedores.wsContrato.GetContratosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetContratos", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsContrato.GetContratosResponse> GetContratosAsync(Mantenedores.wsContrato.GetContratosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class traerUnContratoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="traerUnContrato", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsContrato.traerUnContratoRequestBody Body;
        
        public traerUnContratoRequest() {
        }
        
        public traerUnContratoRequest(Mantenedores.wsContrato.traerUnContratoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class traerUnContratoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_curso;
        
        public traerUnContratoRequestBody() {
        }
        
        public traerUnContratoRequestBody(int id_curso) {
            this.id_curso = id_curso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class traerUnContratoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="traerUnContratoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsContrato.traerUnContratoResponseBody Body;
        
        public traerUnContratoResponse() {
        }
        
        public traerUnContratoResponse(Mantenedores.wsContrato.traerUnContratoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class traerUnContratoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsContrato.Contrato traerUnContratoResult;
        
        public traerUnContratoResponseBody() {
        }
        
        public traerUnContratoResponseBody(Mantenedores.wsContrato.Contrato traerUnContratoResult) {
            this.traerUnContratoResult = traerUnContratoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContratosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContratos", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsContrato.GetContratosRequestBody Body;
        
        public GetContratosRequest() {
        }
        
        public GetContratosRequest(Mantenedores.wsContrato.GetContratosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContratosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_curso;
        
        public GetContratosRequestBody() {
        }
        
        public GetContratosRequestBody(int id_curso) {
            this.id_curso = id_curso;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetContratosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetContratosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsContrato.GetContratosResponseBody Body;
        
        public GetContratosResponse() {
        }
        
        public GetContratosResponse(Mantenedores.wsContrato.GetContratosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetContratosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsContrato.Contrato[] GetContratosResult;
        
        public GetContratosResponseBody() {
        }
        
        public GetContratosResponseBody(Mantenedores.wsContrato.Contrato[] GetContratosResult) {
            this.GetContratosResult = GetContratosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsContratoSoapChannel : Mantenedores.wsContrato.wsContratoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsContratoSoapClient : System.ServiceModel.ClientBase<Mantenedores.wsContrato.wsContratoSoap>, Mantenedores.wsContrato.wsContratoSoap {
        
        public wsContratoSoapClient() {
        }
        
        public wsContratoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsContratoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsContratoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsContratoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsContrato.traerUnContratoResponse Mantenedores.wsContrato.wsContratoSoap.traerUnContrato(Mantenedores.wsContrato.traerUnContratoRequest request) {
            return base.Channel.traerUnContrato(request);
        }
        
        public Mantenedores.wsContrato.Contrato traerUnContrato(int id_curso) {
            Mantenedores.wsContrato.traerUnContratoRequest inValue = new Mantenedores.wsContrato.traerUnContratoRequest();
            inValue.Body = new Mantenedores.wsContrato.traerUnContratoRequestBody();
            inValue.Body.id_curso = id_curso;
            Mantenedores.wsContrato.traerUnContratoResponse retVal = ((Mantenedores.wsContrato.wsContratoSoap)(this)).traerUnContrato(inValue);
            return retVal.Body.traerUnContratoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsContrato.traerUnContratoResponse> Mantenedores.wsContrato.wsContratoSoap.traerUnContratoAsync(Mantenedores.wsContrato.traerUnContratoRequest request) {
            return base.Channel.traerUnContratoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsContrato.traerUnContratoResponse> traerUnContratoAsync(int id_curso) {
            Mantenedores.wsContrato.traerUnContratoRequest inValue = new Mantenedores.wsContrato.traerUnContratoRequest();
            inValue.Body = new Mantenedores.wsContrato.traerUnContratoRequestBody();
            inValue.Body.id_curso = id_curso;
            return ((Mantenedores.wsContrato.wsContratoSoap)(this)).traerUnContratoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsContrato.GetContratosResponse Mantenedores.wsContrato.wsContratoSoap.GetContratos(Mantenedores.wsContrato.GetContratosRequest request) {
            return base.Channel.GetContratos(request);
        }
        
        public Mantenedores.wsContrato.Contrato[] GetContratos(int id_curso) {
            Mantenedores.wsContrato.GetContratosRequest inValue = new Mantenedores.wsContrato.GetContratosRequest();
            inValue.Body = new Mantenedores.wsContrato.GetContratosRequestBody();
            inValue.Body.id_curso = id_curso;
            Mantenedores.wsContrato.GetContratosResponse retVal = ((Mantenedores.wsContrato.wsContratoSoap)(this)).GetContratos(inValue);
            return retVal.Body.GetContratosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsContrato.GetContratosResponse> Mantenedores.wsContrato.wsContratoSoap.GetContratosAsync(Mantenedores.wsContrato.GetContratosRequest request) {
            return base.Channel.GetContratosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsContrato.GetContratosResponse> GetContratosAsync(int id_curso) {
            Mantenedores.wsContrato.GetContratosRequest inValue = new Mantenedores.wsContrato.GetContratosRequest();
            inValue.Body = new Mantenedores.wsContrato.GetContratosRequestBody();
            inValue.Body.id_curso = id_curso;
            return ((Mantenedores.wsContrato.wsContratoSoap)(this)).GetContratosAsync(inValue);
        }
    }
}
