//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mantenedores.wsApoderado {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Apoderado", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Apoderado : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_completoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ap_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ap_maternoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre_completo {
            get {
                return this.Nombre_completoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_completoField, value) != true)) {
                    this.Nombre_completoField = value;
                    this.RaisePropertyChanged("Nombre_completo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ap_paterno {
            get {
                return this.Ap_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ap_paternoField, value) != true)) {
                    this.Ap_paternoField = value;
                    this.RaisePropertyChanged("Ap_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ap_materno {
            get {
                return this.Ap_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ap_maternoField, value) != true)) {
                    this.Ap_maternoField = value;
                    this.RaisePropertyChanged("Ap_materno");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Curso", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Curso : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NivelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LetraField;
        
        private int GradoField;
        
        private int Id_colegioField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nivel {
            get {
                return this.NivelField;
            }
            set {
                if ((object.ReferenceEquals(this.NivelField, value) != true)) {
                    this.NivelField = value;
                    this.RaisePropertyChanged("Nivel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Letra {
            get {
                return this.LetraField;
            }
            set {
                if ((object.ReferenceEquals(this.LetraField, value) != true)) {
                    this.LetraField = value;
                    this.RaisePropertyChanged("Letra");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Grado {
            get {
                return this.GradoField;
            }
            set {
                if ((this.GradoField.Equals(value) != true)) {
                    this.GradoField = value;
                    this.RaisePropertyChanged("Grado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Id_colegio {
            get {
                return this.Id_colegioField;
            }
            set {
                if ((this.Id_colegioField.Equals(value) != true)) {
                    this.Id_colegioField = value;
                    this.RaisePropertyChanged("Id_colegio");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Alumno", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Alumno : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RutField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_completoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ap_paternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ap_maternoField;
        
        private int Id_cursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Rut_apoderadoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Rut {
            get {
                return this.RutField;
            }
            set {
                if ((object.ReferenceEquals(this.RutField, value) != true)) {
                    this.RutField = value;
                    this.RaisePropertyChanged("Rut");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Nombre_completo {
            get {
                return this.Nombre_completoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_completoField, value) != true)) {
                    this.Nombre_completoField = value;
                    this.RaisePropertyChanged("Nombre_completo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Ap_paterno {
            get {
                return this.Ap_paternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ap_paternoField, value) != true)) {
                    this.Ap_paternoField = value;
                    this.RaisePropertyChanged("Ap_paterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ap_materno {
            get {
                return this.Ap_maternoField;
            }
            set {
                if ((object.ReferenceEquals(this.Ap_maternoField, value) != true)) {
                    this.Ap_maternoField = value;
                    this.RaisePropertyChanged("Ap_materno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int Id_curso {
            get {
                return this.Id_cursoField;
            }
            set {
                if ((this.Id_cursoField.Equals(value) != true)) {
                    this.Id_cursoField = value;
                    this.RaisePropertyChanged("Id_curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Rut_apoderado {
            get {
                return this.Rut_apoderadoField;
            }
            set {
                if ((object.ReferenceEquals(this.Rut_apoderadoField, value) != true)) {
                    this.Rut_apoderadoField = value;
                    this.RaisePropertyChanged("Rut_apoderado");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wsApoderado.wsApoderadoSoap")]
    public interface wsApoderadoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByUsername", ReplyAction="*")]
        Mantenedores.wsApoderado.ReadByUsernameResponse ReadByUsername(Mantenedores.wsApoderado.ReadByUsernameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadByUsername", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsApoderado.ReadByUsernameResponse> ReadByUsernameAsync(Mantenedores.wsApoderado.ReadByUsernameRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCursos", ReplyAction="*")]
        Mantenedores.wsApoderado.GetCursosResponse GetCursos(Mantenedores.wsApoderado.GetCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCursos", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetCursosResponse> GetCursosAsync(Mantenedores.wsApoderado.GetCursosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCursosByColegio", ReplyAction="*")]
        Mantenedores.wsApoderado.GetCursosByColegioResponse GetCursosByColegio(Mantenedores.wsApoderado.GetCursosByColegioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCursosByColegio", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetCursosByColegioResponse> GetCursosByColegioAsync(Mantenedores.wsApoderado.GetCursosByColegioRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlumnosInCursos", ReplyAction="*")]
        Mantenedores.wsApoderado.GetAlumnosInCursosResponse GetAlumnosInCursos(Mantenedores.wsApoderado.GetAlumnosInCursosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlumnosInCursos", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetAlumnosInCursosResponse> GetAlumnosInCursosAsync(Mantenedores.wsApoderado.GetAlumnosInCursosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento rut_apoderado del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlumnoByRut", ReplyAction="*")]
        Mantenedores.wsApoderado.GetAlumnoByRutResponse GetAlumnoByRut(Mantenedores.wsApoderado.GetAlumnoByRutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlumnoByRut", ReplyAction="*")]
        System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetAlumnoByRutResponse> GetAlumnoByRutAsync(Mantenedores.wsApoderado.GetAlumnoByRutRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadByUsernameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadByUsername", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsApoderado.ReadByUsernameRequestBody Body;
        
        public ReadByUsernameRequest() {
        }
        
        public ReadByUsernameRequest(Mantenedores.wsApoderado.ReadByUsernameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadByUsernameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        public ReadByUsernameRequestBody() {
        }
        
        public ReadByUsernameRequestBody(string username) {
            this.username = username;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReadByUsernameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReadByUsernameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsApoderado.ReadByUsernameResponseBody Body;
        
        public ReadByUsernameResponse() {
        }
        
        public ReadByUsernameResponse(Mantenedores.wsApoderado.ReadByUsernameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReadByUsernameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsApoderado.Apoderado ReadByUsernameResult;
        
        public ReadByUsernameResponseBody() {
        }
        
        public ReadByUsernameResponseBody(Mantenedores.wsApoderado.Apoderado ReadByUsernameResult) {
            this.ReadByUsernameResult = ReadByUsernameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCursosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCursos", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsApoderado.GetCursosRequestBody Body;
        
        public GetCursosRequest() {
        }
        
        public GetCursosRequest(Mantenedores.wsApoderado.GetCursosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCursosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        public GetCursosRequestBody() {
        }
        
        public GetCursosRequestBody(string rut) {
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCursosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCursosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsApoderado.GetCursosResponseBody Body;
        
        public GetCursosResponse() {
        }
        
        public GetCursosResponse(Mantenedores.wsApoderado.GetCursosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCursosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsApoderado.Curso[] GetCursosResult;
        
        public GetCursosResponseBody() {
        }
        
        public GetCursosResponseBody(Mantenedores.wsApoderado.Curso[] GetCursosResult) {
            this.GetCursosResult = GetCursosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCursosByColegioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCursosByColegio", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsApoderado.GetCursosByColegioRequestBody Body;
        
        public GetCursosByColegioRequest() {
        }
        
        public GetCursosByColegioRequest(Mantenedores.wsApoderado.GetCursosByColegioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCursosByColegioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int id_colegio;
        
        public GetCursosByColegioRequestBody() {
        }
        
        public GetCursosByColegioRequestBody(string rut, int id_colegio) {
            this.rut = rut;
            this.id_colegio = id_colegio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCursosByColegioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCursosByColegioResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsApoderado.GetCursosByColegioResponseBody Body;
        
        public GetCursosByColegioResponse() {
        }
        
        public GetCursosByColegioResponse(Mantenedores.wsApoderado.GetCursosByColegioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCursosByColegioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsApoderado.Curso[] GetCursosByColegioResult;
        
        public GetCursosByColegioResponseBody() {
        }
        
        public GetCursosByColegioResponseBody(Mantenedores.wsApoderado.Curso[] GetCursosByColegioResult) {
            this.GetCursosByColegioResult = GetCursosByColegioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlumnosInCursosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlumnosInCursos", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsApoderado.GetAlumnosInCursosRequestBody Body;
        
        public GetAlumnosInCursosRequest() {
        }
        
        public GetAlumnosInCursosRequest(Mantenedores.wsApoderado.GetAlumnosInCursosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlumnosInCursosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id_curso;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rut;
        
        public GetAlumnosInCursosRequestBody() {
        }
        
        public GetAlumnosInCursosRequestBody(int id_curso, string rut) {
            this.id_curso = id_curso;
            this.rut = rut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlumnosInCursosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlumnosInCursosResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsApoderado.GetAlumnosInCursosResponseBody Body;
        
        public GetAlumnosInCursosResponse() {
        }
        
        public GetAlumnosInCursosResponse(Mantenedores.wsApoderado.GetAlumnosInCursosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlumnosInCursosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsApoderado.Alumno[] GetAlumnosInCursosResult;
        
        public GetAlumnosInCursosResponseBody() {
        }
        
        public GetAlumnosInCursosResponseBody(Mantenedores.wsApoderado.Alumno[] GetAlumnosInCursosResult) {
            this.GetAlumnosInCursosResult = GetAlumnosInCursosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlumnoByRutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlumnoByRut", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsApoderado.GetAlumnoByRutRequestBody Body;
        
        public GetAlumnoByRutRequest() {
        }
        
        public GetAlumnoByRutRequest(Mantenedores.wsApoderado.GetAlumnoByRutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlumnoByRutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string rut_apoderado;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string rut_alumno;
        
        public GetAlumnoByRutRequestBody() {
        }
        
        public GetAlumnoByRutRequestBody(string rut_apoderado, string rut_alumno) {
            this.rut_apoderado = rut_apoderado;
            this.rut_alumno = rut_alumno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlumnoByRutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlumnoByRutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mantenedores.wsApoderado.GetAlumnoByRutResponseBody Body;
        
        public GetAlumnoByRutResponse() {
        }
        
        public GetAlumnoByRutResponse(Mantenedores.wsApoderado.GetAlumnoByRutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlumnoByRutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mantenedores.wsApoderado.Alumno GetAlumnoByRutResult;
        
        public GetAlumnoByRutResponseBody() {
        }
        
        public GetAlumnoByRutResponseBody(Mantenedores.wsApoderado.Alumno GetAlumnoByRutResult) {
            this.GetAlumnoByRutResult = GetAlumnoByRutResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsApoderadoSoapChannel : Mantenedores.wsApoderado.wsApoderadoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsApoderadoSoapClient : System.ServiceModel.ClientBase<Mantenedores.wsApoderado.wsApoderadoSoap>, Mantenedores.wsApoderado.wsApoderadoSoap {
        
        public wsApoderadoSoapClient() {
        }
        
        public wsApoderadoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsApoderadoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsApoderadoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsApoderadoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsApoderado.ReadByUsernameResponse Mantenedores.wsApoderado.wsApoderadoSoap.ReadByUsername(Mantenedores.wsApoderado.ReadByUsernameRequest request) {
            return base.Channel.ReadByUsername(request);
        }
        
        public Mantenedores.wsApoderado.Apoderado ReadByUsername(string username) {
            Mantenedores.wsApoderado.ReadByUsernameRequest inValue = new Mantenedores.wsApoderado.ReadByUsernameRequest();
            inValue.Body = new Mantenedores.wsApoderado.ReadByUsernameRequestBody();
            inValue.Body.username = username;
            Mantenedores.wsApoderado.ReadByUsernameResponse retVal = ((Mantenedores.wsApoderado.wsApoderadoSoap)(this)).ReadByUsername(inValue);
            return retVal.Body.ReadByUsernameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsApoderado.ReadByUsernameResponse> Mantenedores.wsApoderado.wsApoderadoSoap.ReadByUsernameAsync(Mantenedores.wsApoderado.ReadByUsernameRequest request) {
            return base.Channel.ReadByUsernameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsApoderado.ReadByUsernameResponse> ReadByUsernameAsync(string username) {
            Mantenedores.wsApoderado.ReadByUsernameRequest inValue = new Mantenedores.wsApoderado.ReadByUsernameRequest();
            inValue.Body = new Mantenedores.wsApoderado.ReadByUsernameRequestBody();
            inValue.Body.username = username;
            return ((Mantenedores.wsApoderado.wsApoderadoSoap)(this)).ReadByUsernameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsApoderado.GetCursosResponse Mantenedores.wsApoderado.wsApoderadoSoap.GetCursos(Mantenedores.wsApoderado.GetCursosRequest request) {
            return base.Channel.GetCursos(request);
        }
        
        public Mantenedores.wsApoderado.Curso[] GetCursos(string rut) {
            Mantenedores.wsApoderado.GetCursosRequest inValue = new Mantenedores.wsApoderado.GetCursosRequest();
            inValue.Body = new Mantenedores.wsApoderado.GetCursosRequestBody();
            inValue.Body.rut = rut;
            Mantenedores.wsApoderado.GetCursosResponse retVal = ((Mantenedores.wsApoderado.wsApoderadoSoap)(this)).GetCursos(inValue);
            return retVal.Body.GetCursosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetCursosResponse> Mantenedores.wsApoderado.wsApoderadoSoap.GetCursosAsync(Mantenedores.wsApoderado.GetCursosRequest request) {
            return base.Channel.GetCursosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetCursosResponse> GetCursosAsync(string rut) {
            Mantenedores.wsApoderado.GetCursosRequest inValue = new Mantenedores.wsApoderado.GetCursosRequest();
            inValue.Body = new Mantenedores.wsApoderado.GetCursosRequestBody();
            inValue.Body.rut = rut;
            return ((Mantenedores.wsApoderado.wsApoderadoSoap)(this)).GetCursosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsApoderado.GetCursosByColegioResponse Mantenedores.wsApoderado.wsApoderadoSoap.GetCursosByColegio(Mantenedores.wsApoderado.GetCursosByColegioRequest request) {
            return base.Channel.GetCursosByColegio(request);
        }
        
        public Mantenedores.wsApoderado.Curso[] GetCursosByColegio(string rut, int id_colegio) {
            Mantenedores.wsApoderado.GetCursosByColegioRequest inValue = new Mantenedores.wsApoderado.GetCursosByColegioRequest();
            inValue.Body = new Mantenedores.wsApoderado.GetCursosByColegioRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.id_colegio = id_colegio;
            Mantenedores.wsApoderado.GetCursosByColegioResponse retVal = ((Mantenedores.wsApoderado.wsApoderadoSoap)(this)).GetCursosByColegio(inValue);
            return retVal.Body.GetCursosByColegioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetCursosByColegioResponse> Mantenedores.wsApoderado.wsApoderadoSoap.GetCursosByColegioAsync(Mantenedores.wsApoderado.GetCursosByColegioRequest request) {
            return base.Channel.GetCursosByColegioAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetCursosByColegioResponse> GetCursosByColegioAsync(string rut, int id_colegio) {
            Mantenedores.wsApoderado.GetCursosByColegioRequest inValue = new Mantenedores.wsApoderado.GetCursosByColegioRequest();
            inValue.Body = new Mantenedores.wsApoderado.GetCursosByColegioRequestBody();
            inValue.Body.rut = rut;
            inValue.Body.id_colegio = id_colegio;
            return ((Mantenedores.wsApoderado.wsApoderadoSoap)(this)).GetCursosByColegioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsApoderado.GetAlumnosInCursosResponse Mantenedores.wsApoderado.wsApoderadoSoap.GetAlumnosInCursos(Mantenedores.wsApoderado.GetAlumnosInCursosRequest request) {
            return base.Channel.GetAlumnosInCursos(request);
        }
        
        public Mantenedores.wsApoderado.Alumno[] GetAlumnosInCursos(int id_curso, string rut) {
            Mantenedores.wsApoderado.GetAlumnosInCursosRequest inValue = new Mantenedores.wsApoderado.GetAlumnosInCursosRequest();
            inValue.Body = new Mantenedores.wsApoderado.GetAlumnosInCursosRequestBody();
            inValue.Body.id_curso = id_curso;
            inValue.Body.rut = rut;
            Mantenedores.wsApoderado.GetAlumnosInCursosResponse retVal = ((Mantenedores.wsApoderado.wsApoderadoSoap)(this)).GetAlumnosInCursos(inValue);
            return retVal.Body.GetAlumnosInCursosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetAlumnosInCursosResponse> Mantenedores.wsApoderado.wsApoderadoSoap.GetAlumnosInCursosAsync(Mantenedores.wsApoderado.GetAlumnosInCursosRequest request) {
            return base.Channel.GetAlumnosInCursosAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetAlumnosInCursosResponse> GetAlumnosInCursosAsync(int id_curso, string rut) {
            Mantenedores.wsApoderado.GetAlumnosInCursosRequest inValue = new Mantenedores.wsApoderado.GetAlumnosInCursosRequest();
            inValue.Body = new Mantenedores.wsApoderado.GetAlumnosInCursosRequestBody();
            inValue.Body.id_curso = id_curso;
            inValue.Body.rut = rut;
            return ((Mantenedores.wsApoderado.wsApoderadoSoap)(this)).GetAlumnosInCursosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mantenedores.wsApoderado.GetAlumnoByRutResponse Mantenedores.wsApoderado.wsApoderadoSoap.GetAlumnoByRut(Mantenedores.wsApoderado.GetAlumnoByRutRequest request) {
            return base.Channel.GetAlumnoByRut(request);
        }
        
        public Mantenedores.wsApoderado.Alumno GetAlumnoByRut(string rut_apoderado, string rut_alumno) {
            Mantenedores.wsApoderado.GetAlumnoByRutRequest inValue = new Mantenedores.wsApoderado.GetAlumnoByRutRequest();
            inValue.Body = new Mantenedores.wsApoderado.GetAlumnoByRutRequestBody();
            inValue.Body.rut_apoderado = rut_apoderado;
            inValue.Body.rut_alumno = rut_alumno;
            Mantenedores.wsApoderado.GetAlumnoByRutResponse retVal = ((Mantenedores.wsApoderado.wsApoderadoSoap)(this)).GetAlumnoByRut(inValue);
            return retVal.Body.GetAlumnoByRutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetAlumnoByRutResponse> Mantenedores.wsApoderado.wsApoderadoSoap.GetAlumnoByRutAsync(Mantenedores.wsApoderado.GetAlumnoByRutRequest request) {
            return base.Channel.GetAlumnoByRutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Mantenedores.wsApoderado.GetAlumnoByRutResponse> GetAlumnoByRutAsync(string rut_apoderado, string rut_alumno) {
            Mantenedores.wsApoderado.GetAlumnoByRutRequest inValue = new Mantenedores.wsApoderado.GetAlumnoByRutRequest();
            inValue.Body = new Mantenedores.wsApoderado.GetAlumnoByRutRequestBody();
            inValue.Body.rut_apoderado = rut_apoderado;
            inValue.Body.rut_alumno = rut_alumno;
            return ((Mantenedores.wsApoderado.wsApoderadoSoap)(this)).GetAlumnoByRutAsync(inValue);
        }
    }
}
